import configparser
import json
import os

configPath = "/home/subado/.config/dunst/dunstrc"

if not os.path.exists(configPath):
    print("dunstrc not found")
    exit

# Read dunstrc
config = configparser.ConfigParser()
config.read(configPath)


def colorSet(section: str, option: str, color: str):
    config.set(section, option, '"' + color + '"')


# Load json with colors generated by wal
with open('/home/subado/.cache/wal/colors.json', "r") as file:
    data = json.load(file)

# Copy colors from json to list
colors = []
for i in data['colors']:
    colors.append(data['colors'][i])

# Set global colors
colorSet("global", "frame_color", colors[8])

# Set urgency_low colors
colorSet("urgency_low", "background", colors[0])
colorSet("urgency_low", "foreground", colors[7])
colorSet("urgency_low", "highlight", colors[2])

# Set urgency_normal colors
colorSet("urgency_normal", "background", colors[0])
colorSet("urgency_normal", "foreground", colors[15])
colorSet("urgency_normal", "highlight", colors[13])

# Set urgency_critical colors
colorSet("urgency_critical", "background", colors[1])
colorSet("urgency_critical", "foreground", colors[15])
colorSet("urgency_critical", "highlight", colors[9])

# Write changes in config to config file
with open(configPath, "w") as configFile:
    config.write(configFile)
